version = 1

test_patterns = ["**/test/**"]

exclude_patterns = [
    "static/**",
    "deploy/**",
    "contributions/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "browser",
    "cypress"
  ]
  cyclomatic_complexity_threshold = "critical"
  dialect = "typescript"
  dependency_file_paths = [
  '/app/client/'
  ]
